from rsf.proj import *
Flow('overthrust',['overthrust.vites.h','overthrust.vites'],
     '''
     (cat ${SOURCES[0]} ; echo data_format=xdr_float) |
     dd form=native | put label1=X label2=Y label3=Z 
     unit1=m unit2=m unit3=m  label=Velocity 
     unit=m/s d1=25 d2=25 d3=25
     ''',stdin=0)

# submuestrea volumen de datos y transpone los ejes X-Z
Flow('overthrust_sample','overthrust',
    '''window j1=2 j2=2 j3=2 | transp plane=13 ''')

Result('overthrust_sample',
       '''
       byte gainpanel=all mean=y | transp plane=23 |
       grey3 flat=n frame1=5 frame2=50 frame3=50
       title="SEG/EAGE Overthrust Model"
       color=j point1=0.6 point2=0.6
       screenratio=0.31
       ''')
End()  
